services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jpa
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynet
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/jwt-app:latest
    container_name: backend
    ports:
      - "8087:8087"
    volumes:
      - upload-images:/app/images
    environment:
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul -Dfile.encoding=UTF-8"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    networks:
      - mynet
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/lov3-frontend:latest
    container_name: frontend
    ports:
      - "80:80"                          # 외부에서 80포트로 접근 → Nginx가 처리
    depends_on:
      - backend
    networks:
      - mynet
    restart: unless-stopped

volumes:
  upload-images:
  mysql-data:                            # DB 데이터 영구 보존

networks:
  mynet:
    external: true
