spring.application.name=lov3_board_project

server.port=8087

spring.profiles.active=dev

spring.jwt.secret=LOV3-BOARD-JWT-SECRET-KEY-change-this-in-production

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql

spring.jackson.serialization.write-dates-as-timestamps=false