# ===== 운영환경 DB 설정 (환경변수로 주입) =====
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# ===== 운영환경 JWT (환경변수로 주입) =====
spring.jwt.secret=${SPRING_JWT_SECRET}

# ===== 운영환경 테이블 설정 (데이터 유지) =====
spring.jpa.hibernate.ddl-auto=none
